### ISSUE TITLE
PKGSEC-0001/0002 incorrectly flags other JSON files

### ISSUE THREAD

**Issue by artis3n** [rallyhealth/conftest-policy-packs#10]
PKGSEC-0001 requires Node projects using a `package.json` file to wrap their package name underneath an organization scope. It relies on the [is_package_json](https://github.com/rallyhealth/conftest-policy-packs/blob/main/policies/lib/packages_functions.rego#L8) utility function in `lib/packages_functions.rego`.

The only required top-level fields in a `package.json` file are `name` and `version`, so those are checked for existence to determine whether the JSON file we're evaluating is a `package.json` file. This is not granular enough and the policy incorrectly flags unrelated JSON files with this policy.

The "best" way to resolve this would be for conftest to include file metadata in the `data` available when evaluating a policy. I originally filed this against opa with https://github.com/open-policy-agent/opa/issues/3662 and never followed up to file an issue with conftest. I'll do that [now](https://github.com/open-policy-agent/conftest/issues/604).

Not sure if there are alternative solutions to make the policy more accurate.

**Comment by artis3n** [comment]
It is probably sufficient to look for a "dependencies" key alongside "name" and "version." Not _technically_ required for a package.json file but we can be pretty confident it would exist. That would likely reduce the false positive hit rate considerably.

**Comment by Sburris** [comment]
Something else to consider, how do we distinguish between package.json file in the application under review vs if a npm package's package.json ends up in the source code repo.  They would get flagged for not having engines/node defined.

**Comment by artis3n** [comment]
> Something else to consider, how do we distinguish between package.json file in the application under review vs if a npm package's package.json ends up in the source code repo. They would get flagged for not having engines/node defined.

That I think we should handle outside of the Rego policy, in the ingestion to conftest.

**Comment by Sburris** [comment]
> That I think we should handle outside of the Rego policy, in the ingestion to conftest.
Sure, but I think we need to define/document those assumptions somewhere.  Possibly start creating some ADRs to capture that decision (0001 being the "we are going to use ADRs", and 0002 having the assumption that no third party dependencies [or whatever wording] will be sent.)  Then updating the README with an Assumptions/constraints area where we define that for consumers of this library.

Depending on how this goes, I can put together a PR that has these changes in it.

**Comment by artis3n** [comment]
Next conftest version should resolve the concern! https://github.com/open-policy-agent/conftest/pull/610

**Comment by artis3n** [comment]
Resolved in #21
